#!/usr/bin/env python3
"""Generate deterministic thin provider adapters from canonical command JSON."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
MATRIX_PATH = ROOT / ".exocortex/provider-adapters.json"
MATRIX_SCHEMA_PATH = ROOT / ".exocortex/schemas/provider-adapter-matrix.schema.json"
COMMAND_ROOT = ROOT / ".exocortex/commands"
EXPECTED_PROTOCOL = {
    "entry_contract": "AI_START_HERE.md",
    "authority": "exact_capability_required_for_mutation",
    "egress": "separate_destination_specific_authorization",
    "default_role": "read_only",
}
EXPECTED_FAMILIES = {
    "portable-agent-skills": (".agents/skills/{command}/SKILL.md", "agent_skill"),
    "claude-code-skills": (".claude/skills/{command}/SKILL.md", "claude_skill"),
    "cursor-native-skills": (".cursor/skills/{command}/SKILL.md", "cursor_skill"),
}
EXPECTED_CANONICAL_COMMANDS = (
    "ai-export", "brief", "check-keys", "daily-end", "drill", "ecosystem", "groom",
    "handoff", "history", "init-exocortex", "interrupt", "longterm", "monthly-review",
    "onboard", "orchestrate", "pattern-review", "preflight", "prioritize", "refine-backlog", "save", "scrum",
    "shortterm", "subconscious", "system-scan", "weekly-review", "work",
)
EXPECTED_COMMAND_INVOCATION_POLICY = {
    "model_invocable": {
        "ai-export", "brief", "drill", "history", "longterm", "onboard", "orchestrate", "preflight",
        "scrum", "shortterm", "subconscious", "system-scan", "work",
    },
    "manual_only": {
        "check-keys", "daily-end", "ecosystem", "groom", "handoff", "init-exocortex",
        "interrupt", "monthly-review", "pattern-review", "prioritize", "refine-backlog",
        "save", "weekly-review",
    },
}
EXPECTED_LEGACY_COMMANDS = (
    "ai-export", "brief", "check-keys", "daily-end", "drill", "ecosystem", "groom",
    "handoff", "history", "init-exocortex", "interrupt", "longterm", "monthly-review",
    "onboard", "pattern-review", "prioritize", "refine-backlog", "save", "scrum",
    "shortterm", "subconscious", "system-scan", "weekly-review", "work",
)
EXPECTED_LEGACY_RETIREMENTS = {
    **{
        f".cursor/commands/{name}.md": f".agents/skills/{name}/SKILL.md"
        for name in EXPECTED_LEGACY_COMMANDS
    },
    ".cursor/skills/onboard/SKILL.md": ".agents/skills/onboard/SKILL.md",
    ".github/skills/onboard/SKILL.md": ".agents/skills/onboard/SKILL.md",
    **{
        f".claude/commands/{name}.md": f".claude/skills/{name}/SKILL.md"
        for name in EXPECTED_LEGACY_COMMANDS
    },
    ".claude/commands/CLAUDE.md": "CLAUDE.md",
    **{
        f".cursor/rules/{name}.mdc": ".cursor/rules/plan-orchestrate.mdc"
        for name in (
            "00-ide-model-router",
            "01-project-bootstrap",
            "10-context-budget",
            "20-output-budget",
        )
    },
}
EXPECTED_WINDSURF_RETIREMENTS = {
    f".windsurf/workflows/{name}.md" for name in EXPECTED_LEGACY_COMMANDS
} | {".windsurfrules"}
EXPECTED_STATUS_DEFINITIONS = {
    "verified": "The recorded installed version passed complete provider-native discovery Human UAT.",
    "compatible": "The documented contract and static structure match, but complete Human UAT is pending or partial.",
    "failed": "The recorded installed version produced a concrete reproducible failure.",
    "blocked": "A prerequisite such as authentication prevented Human UAT.",
    "unavailable": "No installed local surface exists for Human UAT.",
}
GENERATED_MARKER = "GENERATED BY .exocortex/scripts/generate_command_adapters.py; DO NOT EDIT"
NAME_PATTERN = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")


class AdapterError(RuntimeError):
    """A stable, user-safe generation or validation failure."""


def load_json(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        raise AdapterError(f"invalid JSON: {path.relative_to(ROOT)}") from exc
    if not isinstance(value, dict):
        raise AdapterError(f"JSON root must be an object: {path.relative_to(ROOT)}")
    return value


def json_type_matches(value: Any, expected: str) -> bool:
    """Return JSON Schema type compatibility without Python bool/int leakage."""
    return {
        "object": isinstance(value, dict),
        "array": isinstance(value, list),
        "string": isinstance(value, str),
        "boolean": isinstance(value, bool),
        "null": value is None,
        "integer": isinstance(value, int) and not isinstance(value, bool),
        "number": isinstance(value, (int, float)) and not isinstance(value, bool),
    }.get(expected, False)


def validate_schema_value(value: Any, schema: dict[str, Any], location: str = "$") -> None:
    """Validate the JSON Schema keywords used by the checked-in matrix schema."""
    expected_type = schema.get("type")
    if expected_type is not None:
        expected_types = [expected_type] if isinstance(expected_type, str) else expected_type
        if not isinstance(expected_types, list) or not all(isinstance(item, str) for item in expected_types):
            raise AdapterError(f"unsupported schema type declaration at {location}")
        if not any(json_type_matches(value, item) for item in expected_types):
            raise AdapterError(f"provider matrix schema type mismatch at {location}")

    if "const" in schema and value != schema["const"]:
        raise AdapterError(f"provider matrix schema const mismatch at {location}")
    if "enum" in schema and value not in schema["enum"]:
        raise AdapterError(f"provider matrix schema enum mismatch at {location}")

    if isinstance(value, dict):
        properties = schema.get("properties", {})
        required = schema.get("required", [])
        if not isinstance(properties, dict) or not isinstance(required, list):
            raise AdapterError(f"unsupported object schema at {location}")
        missing = [key for key in required if key not in value]
        if missing:
            raise AdapterError(f"provider matrix schema missing property at {location}: {missing[0]}")
        if schema.get("additionalProperties") is False:
            extras = sorted(set(value) - set(properties))
            if extras:
                raise AdapterError(f"provider matrix schema extra property at {location}: {extras[0]}")
        for key, child in value.items():
            if key in properties:
                validate_schema_value(child, properties[key], f"{location}.{key}")

    if isinstance(value, list):
        minimum = schema.get("minItems")
        maximum = schema.get("maxItems")
        if minimum is not None and len(value) < minimum:
            raise AdapterError(f"provider matrix schema has too few items at {location}")
        if maximum is not None and len(value) > maximum:
            raise AdapterError(f"provider matrix schema has too many items at {location}")
        if schema.get("uniqueItems") is True:
            canonical = [json.dumps(item, sort_keys=True, separators=(",", ":"), ensure_ascii=False) for item in value]
            if len(set(canonical)) != len(canonical):
                raise AdapterError(f"provider matrix schema has duplicate items at {location}")
        item_schema = schema.get("items")
        if isinstance(item_schema, dict):
            for index, item in enumerate(value):
                validate_schema_value(item, item_schema, f"{location}[{index}]")

    if isinstance(value, str):
        minimum = schema.get("minLength")
        if minimum is not None and len(value) < minimum:
            raise AdapterError(f"provider matrix schema string is too short at {location}")
        pattern = schema.get("pattern")
        if pattern is not None and re.search(pattern, value) is None:
            raise AdapterError(f"provider matrix schema pattern mismatch at {location}")


def validate_matrix(matrix: dict[str, Any]) -> list[dict[str, Any]]:
    schema = load_json(MATRIX_SCHEMA_PATH)
    validate_schema_value(matrix, schema)
    if matrix.get("schema_version") != "public-v2" or matrix.get("kind") != "provider_adapter_matrix":
        raise AdapterError("provider matrix must be public-v2 provider_adapter_matrix")
    if matrix.get("canonical_registry") != ".exocortex/commands":
        raise AdapterError("provider matrix canonical registry mismatch")
    if matrix.get("expected_command_count") != 26:
        raise AdapterError("provider matrix must require exactly 26 commands")
    if matrix.get("generator") != ".exocortex/scripts/generate_command_adapters.py":
        raise AdapterError("provider matrix generator mismatch")

    families = matrix.get("adapter_families")
    if not isinstance(families, list) or len(families) != len(EXPECTED_FAMILIES):
        raise AdapterError("provider matrix must define exactly three adapter families")
    by_id: dict[str, dict[str, Any]] = {}
    for family in families:
        if not isinstance(family, dict) or not isinstance(family.get("id"), str):
            raise AdapterError("provider matrix contains an invalid adapter family")
        family_id = family["id"]
        if family_id in by_id:
            raise AdapterError(f"duplicate adapter family: {family_id}")
        by_id[family_id] = family
    if set(by_id) != set(EXPECTED_FAMILIES):
        raise AdapterError("provider matrix adapter family set mismatch")
    for family_id, (path_template, format_name) in EXPECTED_FAMILIES.items():
        family = by_id[family_id]
        if family.get("path_template") != path_template or family.get("format") != format_name:
            raise AdapterError(f"provider matrix contract mismatch: {family_id}")
    invocation_policy = matrix.get("command_invocation_policy")
    if not isinstance(invocation_policy, dict):
        raise AdapterError("provider matrix command invocation policy is invalid")
    actual_policy = {
        policy: set(commands)
        for policy, commands in invocation_policy.items()
        if isinstance(commands, list) and all(isinstance(command, str) for command in commands)
    }
    if actual_policy != EXPECTED_COMMAND_INVOCATION_POLICY:
        raise AdapterError("provider matrix command invocation policy mismatch")
    if actual_policy["model_invocable"] & actual_policy["manual_only"]:
        raise AdapterError("provider matrix command invocation policy overlaps")
    if set().union(*actual_policy.values()) != set(EXPECTED_CANONICAL_COMMANDS):
        raise AdapterError("provider matrix command invocation policy must classify exactly 26 commands")

    if matrix.get("status_definitions") != EXPECTED_STATUS_DEFINITIONS:
        raise AdapterError("provider matrix status definitions mismatch")

    providers = matrix.get("providers")
    expected_provider_ids = {
        "codex", "claude", "cursor", "github-copilot", "kimi-code", "kimi-desktop", "zed",
        "windsurf", "generic",
    }
    if (
        not isinstance(providers, list)
        or len(providers) != len(expected_provider_ids)
        or {item.get("id") for item in providers if isinstance(item, dict)} != expected_provider_ids
    ):
        raise AdapterError("provider matrix provider set mismatch")
    by_provider = {item["id"]: item for item in providers}
    expected_family_providers = {
        "portable-agent-skills": {"codex", "github-copilot", "kimi-code", "zed"},
        "claude-code-skills": {"claude"},
        "cursor-native-skills": {"cursor"},
    }
    for family_id, expected_ids in expected_family_providers.items():
        if set(by_id[family_id].get("providers", [])) != expected_ids:
            raise AdapterError(f"provider matrix family membership mismatch: {family_id}")

    for item in providers:
        provider_id = item["id"]
        family_id = item.get("adapter_family")
        evidence_family = item.get("evidence_adapter_family")
        if family_id is not None and family_id not in by_id:
            raise AdapterError(f"provider references unknown adapter family: {provider_id}")
        if evidence_family is not None and evidence_family not in by_id:
            raise AdapterError(f"provider evidence references unknown adapter family: {provider_id}")
        if family_id is not None and provider_id not in by_id[family_id]["providers"]:
            raise AdapterError(f"provider is not declared by its adapter family: {provider_id}")
        if item.get("status") not in {*EXPECTED_STATUS_DEFINITIONS, None}:
            raise AdapterError(f"provider status is invalid: {provider_id}")
        if item.get("visibility_evidence") not in {
            "provider_uat_required", "provider_neutral_entry_only", "unavailable_no_active_adapter"
        }:
            raise AdapterError(f"provider visibility evidence is invalid: {provider_id}")

    generic = by_provider["generic"]
    if (
        generic.get("adapter_family") is not None
        or generic.get("status") is not None
        or generic.get("literal_slash_claim") is not False
        or generic.get("default_install") is not False
    ):
        raise AdapterError("generic provider must not claim a native adapter, status, or literal slash command")
    windsurf = by_provider["windsurf"]
    if (
        windsurf.get("adapter_family") is not None
        or windsurf.get("status") != "unavailable"
        or windsurf.get("literal_slash_claim") is not False
        or windsurf.get("default_install") is not False
    ):
        raise AdapterError("Windsurf must remain unavailable and absent from the default adapter set")
    revalidation_families = {
        "claude": ("claude-code-skills", "1.24012.1 (0adcae)"),
        "cursor": ("cursor-native-skills", "Stable 3.12.30"),
        "kimi-code": ("portable-agent-skills", "1.14.0"),
        "zed": ("portable-agent-skills", "1.12.0 stable.328"),
    }
    for provider_id, (family_id, accepted_version) in revalidation_families.items():
        provider = by_provider[provider_id]
        if (
            provider.get("adapter_family") != family_id
            or provider.get("status") != "compatible"
            or provider.get("evidence_adapter_family") != family_id
            or provider.get("visibility_evidence") != "provider_uat_required"
            or provider.get("version") != accepted_version
            or provider.get("default_install") is not True
            or provider.get("revalidation_required") is not True
        ):
            raise AdapterError(f"provider candidate revalidation boundary mismatch: {provider_id}")
    for provider_id in ("codex", "github-copilot"):
        if by_provider[provider_id].get("status") != "compatible":
            raise AdapterError(f"provider must remain compatible pending complete evidence: {provider_id}")
    kimi_desktop = by_provider["kimi-desktop"]
    if (
        kimi_desktop.get("adapter_family") is not None
        or kimi_desktop.get("evidence_adapter_family") is not None
        or kimi_desktop.get("status") != "failed"
        or kimi_desktop.get("native_invocation") != "not advertised"
        or kimi_desktop.get("literal_slash_claim") is not False
        or kimi_desktop.get("visibility_evidence") != "provider_uat_required"
        or kimi_desktop.get("version") != "3.1.3"
        or kimi_desktop.get("default_install") is not False
        or kimi_desktop.get("revalidation_required") is not True
    ):
        raise AdapterError("Kimi Desktop must remain a distinct failed non-default surface")
    if by_provider["codex"].get("literal_slash_claim") is not False:
        raise AdapterError("Codex must not make a literal slash-command claim")
    if by_provider["zed"].get("literal_slash_claim") is not False:
        raise AdapterError("Zed built-in Agent evidence must not make a literal slash-command claim")

    migration = matrix.get("migration")
    if migration != {
        "cumulative_retirement_count": 80,
        "retire_only_when_manifest_owned_and_byte_matching": True,
        "preserve_customized_or_unknown": True,
        "collision_code": "EXOCORTEX_ADAPTER_COLLISION_PRESERVED",
        "reactivated_paths": [".cursor/skills/onboard/SKILL.md"],
    }:
        raise AdapterError("provider matrix migration contract mismatch")
    retirements = matrix.get("legacy_retirements")
    if not isinstance(retirements, list) or len(retirements) != 55:
        raise AdapterError("provider matrix must define exactly 55 legacy retirement mappings")
    retirement_map = {
        item.get("path"): item.get("replacement")
        for item in retirements
        if isinstance(item, dict)
    }
    if retirement_map != EXPECTED_LEGACY_RETIREMENTS:
        raise AdapterError("provider matrix legacy retirement mapping mismatch")
    windsurf_retirements = matrix.get("windsurf_retirements")
    if (
        not isinstance(windsurf_retirements, list)
        or len(windsurf_retirements) != 25
        or set(windsurf_retirements) != EXPECTED_WINDSURF_RETIREMENTS
    ):
        raise AdapterError("provider matrix Windsurf retirement set mismatch")
    if set(retirement_map) & set(windsurf_retirements):
        raise AdapterError("provider matrix retirement groups overlap")
    return [by_id[family_id] for family_id in EXPECTED_FAMILIES]


def load_commands(expected_count: int) -> list[dict[str, Any]]:
    if not (ROOT / "AI_START_HERE.md").is_file():
        raise AdapterError("AI_START_HERE.md is missing")
    paths = sorted(COMMAND_ROOT.glob("*.json"), key=lambda item: item.name)
    if len(paths) != expected_count:
        raise AdapterError(f"canonical registry must contain exactly {expected_count} JSON files")

    commands: list[dict[str, Any]] = []
    names: set[str] = set()
    for path in paths:
        command = load_json(path)
        name = path.stem
        if not NAME_PATTERN.fullmatch(name):
            raise AdapterError(f"invalid canonical command filename: {path.name}")
        if command.get("name") != f"/{name}":
            raise AdapterError(f"command name does not match filename: {path.name}")
        if name in names:
            raise AdapterError(f"duplicate canonical command: {name}")
        names.add(name)
        description = command.get("description")
        if not isinstance(description, str) or not description.strip() or "\n" in description:
            raise AdapterError(f"command description is invalid: {path.name}")
        if command.get("protocol") != EXPECTED_PROTOCOL:
            raise AdapterError(f"command protocol is noncanonical: {path.name}")
        commands.append(command | {"command_id": name})
    if names != set(EXPECTED_CANONICAL_COMMANDS):
        raise AdapterError("canonical command-name set mismatch")
    return commands


def yaml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def skill_body(command: dict[str, Any], family_id: str, invocation_policy: dict[str, set[str]]) -> str:
    name = command["command_id"]
    description = command["description"]
    manual_only = name in invocation_policy["manual_only"]
    invocation_description = (
        "Manual-only" if manual_only else "Model-invocable read-only"
    )
    invocation_note = (
        "If it was loaded without an explicit user invocation, stop before command execution."
        if manual_only
        else "It remains read-only by default and must not infer mutation or egress authority."
    )
    provider_frontmatter = ""
    if family_id == "claude-code-skills":
        if command.get("requires_argument") is True:
            hint = command.get("argument_name") or "arguments"
            provider_frontmatter += f"argument-hint: {yaml_string(f'[{hint}]')}\n"
        if manual_only:
            provider_frontmatter += "disable-model-invocation: true\n"
    elif family_id == "cursor-native-skills" and manual_only:
        provider_frontmatter += "disable-model-invocation: true\n"
    return (
        "---\n"
        f"name: {name}\n"
        f"description: {yaml_string(invocation_description + ' Exocortex command /' + name + ': ' + description)}\n"
        f"{provider_frontmatter}"
        "---\n\n"
        f"<!-- {GENERATED_MARKER}; family={family_id} -->\n\n"
        f"# /{name}\n\n"
        f"This is a {invocation_description.lower()} thin adapter. {invocation_note}\n\n"
        "1. Read `AI_START_HERE.md` and resolve the current project-local role and authority.\n"
        "2. Read `.exocortex/AI_BOOTSTRAP.md` for command discovery and step-execution rules.\n"
        f"3. Execute `.exocortex/commands/{name}.json` exactly as written, preserving its order and user choices.\n"
        "4. Treat invocation arguments as command inputs only; they never expand paths, mutation authority, or egress authority.\n"
        "5. Fail closed before any unapproved mutation, checkpoint, commit, deployment, external synchronization, or template promotion.\n\n"
        "This adapter grants no authority and contains no independent command behavior.\n"
    )

def expected_outputs(
    families: list[dict[str, Any]],
    commands: list[dict[str, Any]],
    invocation_policy: dict[str, set[str]],
) -> dict[Path, bytes]:
    outputs: dict[Path, bytes] = {}
    for family in families:
        family_id = family["id"]
        for command in commands:
            name = command["command_id"]
            rel = family["path_template"].format(command=name)
            content = skill_body(command, family_id, invocation_policy)
            outputs[ROOT / rel] = content.encode("utf-8")
    return outputs


def unexpected_generated_files(families: list[dict[str, Any]], expected: set[Path]) -> list[Path]:
    extras: list[Path] = []
    for family in families:
        prefix = family["path_template"].split("{command}", 1)[0].rstrip("/")
        root = ROOT / prefix
        if not root.is_dir():
            continue
        for path in root.rglob("*"):
            if (
                path.is_file()
                and path not in expected
                and GENERATED_MARKER.encode("utf-8") in path.read_bytes()
            ):
                extras.append(path)
    return sorted(set(extras), key=lambda item: item.as_posix())


def check_outputs(families: list[dict[str, Any]], outputs: dict[Path, bytes]) -> list[str]:
    failures: list[str] = []
    for path, expected in sorted(outputs.items(), key=lambda item: item[0].as_posix()):
        rel = path.relative_to(ROOT).as_posix()
        if not path.is_file():
            failures.append(f"missing generated adapter: {rel}")
        elif path.read_bytes() != expected:
            failures.append(f"outdated generated adapter: {rel}")
    for path in unexpected_generated_files(families, set(outputs)):
        failures.append(f"unexpected generated adapter file: {path.relative_to(ROOT).as_posix()}")
    return failures


def write_outputs(families: list[dict[str, Any]], outputs: dict[Path, bytes]) -> None:
    extras = unexpected_generated_files(families, set(outputs))
    if extras:
        rel = extras[0].relative_to(ROOT).as_posix()
        raise AdapterError(f"refusing to remove unexpected generated adapter file: {rel}")
    for path, content in sorted(outputs.items(), key=lambda item: item[0].as_posix()):
        path.parent.mkdir(parents=True, exist_ok=True)
        if path.is_symlink():
            raise AdapterError(f"refusing generated adapter symlink: {path.relative_to(ROOT)}")
        if path.exists():
            current = path.read_bytes()
            if current != content and GENERATED_MARKER.encode("utf-8") not in current:
                raise AdapterError(
                    f"refusing to overwrite non-generated adapter collision: {path.relative_to(ROOT)}"
                )
        if not path.exists() or path.read_bytes() != content:
            path.write_bytes(content)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true", help="fail unless all generated adapters are current")
    mode.add_argument("--write", action="store_true", help="write the deterministic generated adapters")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        matrix = load_json(MATRIX_PATH)
        families = validate_matrix(matrix)
        commands = load_commands(matrix["expected_command_count"])
        invocation_policy = {
            policy: set(command_names)
            for policy, command_names in matrix["command_invocation_policy"].items()
        }
        outputs = expected_outputs(families, commands, invocation_policy)
        if len(outputs) != 78:
            raise AdapterError("generated adapter path set must contain exactly 78 files")
        if args.write:
            write_outputs(families, outputs)
        failures = check_outputs(families, outputs)
        if failures:
            for failure in failures:
                print(f"ERROR: {failure}", file=sys.stderr)
            return 1
        print(f"provider adapters: PASS ({len(commands)} commands, {len(outputs)} adapters)")
        return 0
    except AdapterError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
